---
- name: Check system updates and display details
  hosts: all
  tasks:
    - name: Gather system information
      ansible.builtin.setup:

    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Check for available updates
      ansible.builtin.command:
        cmd: "apt list --upgradable"
      register: updates

    - name: Display available updates
      ansible.builtin.debug:
        var: updates.stdout_lines
