---
- name: Check system updates and display details
  hosts: all
  become: yes
  tasks:
    - name: Update the package cache
      apt:
        update_cache: yes

    - name: Check for available updates
      shell: apt list --upgradable
      register: updates

    - name: Format the update results
      set_fact:
        update_list: |
          {% for line in updates.stdout_lines %}
          {% if not line.startswith('Listing...') %}
          {{ line }}
          {% endif %}
          {% endfor %}

    - name: Write the formatted update results to a file
      copy:
        dest: /tmp/system_update_report.txt
        content: |
          ===========================================
          System Update Check - {{ ansible_date_time.date }} {{ ansible_date_time.time }}
          ===========================================
          The following updates are available:
          -------------------------------------

          {% for line in update_list.splitlines() %}
          {{ line }}

          {% endfor %}

    - name: Display system update results in the console
      debug:
        msg: |
          ===========================================
          System Update Check - {{ ansible_date_time.date }} {{ ansible_date_time.time }}
          ===========================================
          The following updates are available:
          -------------------------------------

          {% for line in update_list.splitlines() %}
          {{ line }}

          {% endfor %}
