---
- name: Check system updates and display details
  hosts: all
  become: yes
  tasks:
    - name: Update the package cache
      apt:
        update_cache: yes

    - name: Check for available updates
      shell: apt list --upgradable
      register: updates

    - name: Parse updates into a structured list
      set_fact:
        update_list: >
          {{
            updates.stdout_lines
            | select("search", "^[^Listing]")
            | map("regex_search", "^(\\S+)/(\\S+)\\s+(\\S+)\\s+(\\S+)\\s+\\[(.+)]")
            | map("list")
            | map("flatten")
            | map("zip", ["Package", "Repository", "Version", "Architecture", "Current Version"])
            | map("dict")
            | list
          }}

    - name: Display parsed update details
      debug:
        msg: |
          ===========================================
          System Update Check - {{ ansible_date_time.date }} {{ ansible_date_time.time }}
          ===========================================
          The following updates are available:
          -------------------------------------
          {% for update in update_list %}
          Package: {{ update.Package }}
          Repository: {{ update.Repository }}
          New Version: {{ update.Version }}
          Current Version: {{ update['Current Version'] }}
          Architecture: {{ update.Architecture }}
          -------------------------------------
          {% endfor %}
