---
- name: Check system updates and display details
  hosts: all
  become: yes
  tasks:
    - name: Update the package cache
      apt:
        update_cache: yes

    - name: Check for available updates
      shell: apt list --upgradable 2>/dev/null
      register: updates

    - name: Format the update results
      set_fact:
        update_list: |
          {% set results = [] %}
          {% for line in updates.stdout_lines %}
            {% if not line.startswith('Listing...') %}
              {% set fields = line.split() %}
              {% set package_info = fields[0] + " - Version: " + fields[1] + ", Repository: " + fields[2] %}
              {{ results.append(package_info) }}
            {% endif %}
          {% endfor %}
          {{ results | join('\n') }}

    - name: Display system update results in a readable format
      debug:
        msg: |
          ===========================================
          System Update Check - {{ ansible_date_time.date }} {{ ansible_date_time.time }}
          ===========================================
          The following updates are available:
          -------------------------------------
          {{ update_list if update_list else "No updates available." }}
