---
- name: Check system updates and display details
  hosts: all
  become: yes
  tasks:
    - name: Update the package cache
      apt:
        update_cache: yes

    - name: Check for available updates
      shell: apt list --upgradable
      register: updates

    - name: Display system update results
      debug:
        msg: |
          ===========================================
          System Update Check - {{ ansible_date_time.date }} {{ ansible_date_time.time }}
          ===========================================
          The following updates are available:
          -------------------------------------

          {{ updates.stdout }}
